### PR TITLE
Code cleanups, added coverage command for group list

### PR DESCRIPTION
**Pull request by marksteele**

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Thanks for the PR!  Are you using `riak_pg`?

**Comment by cmeiklejohn** [comment]
:+1: looks great; thanks!

**Comment by marksteele** [comment]
I probably will be using it shortly.

I had written something that was almost the same when I came across riak_pg (riak core app, crdts in a dict). Figured I wouldn't duplicate efforts.

A few things to consider as improvements (which I may start working on): Move to a crdt map instead of a dict, have coordinating node add a monitor to pids for active pruning, filtering out empty groups in the coverage command.

Cheers

**Comment by cmeiklejohn** [comment]
For sure.  At the time of implementation and when we wrote the paper, the CRDT map did not yet exist, and the ORSWOT didn't either.  So, there's definitely a lot of possible improvement there.

**Pull request merged**
