### PR TITLE
Switching from dict to CRDT map

### PR DESCRIPTION
**Pull request by marksteele**
Appears to work. Caveats are that my erlang-fu isn't yet masterful, and you're much more likely to spot issues with the CRDT changes than I am.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Seems straightforward.  I'd feel more confident with a EQC test, so maybe we can work together on one.  Once change I'm going to make is to add a 'locked-deps' target, similar to how Riak is built.

**Comment by cmeiklejohn** [comment]
:+1:

**Comment by marksteele** [comment]
Would be happy to help, however I don't have any experience with quickcheck. Any pointers on getting started testing riak_core apps with quickcheck?

**Comment by cmeiklejohn** [comment]
Unfortunately, it's very difficult.  We've been fighting with this while performing our work on Lasp.

**Comment by marksteele** [comment]
I was actually looking at Lasp hoping for an easy example to follow.

I'll start reading up on quickcheck test design, but it's going to take a little while to get up to speed. In the interim if you have some ideas please share.

**Pull request merged**
