### PR TITLE
Fixed a race condition on repair, removed create call as it's essenti…

### PR DESCRIPTION
**Pull request by marksteele**
…ally useless

Also, not that I'm going for fame or anything, but what is the etiquette for adding to author tags?

### CODE REVIEW

**Comment by marksteele** [comment]
Ugh, there's still more races in there methinks.

**Comment by cmeiklejohn** [comment]
Feel free to add yourself to any files you've worked on.

**Comment by cmeiklejohn** [comment]
Can you amend the commit with more information as to what the race condition is?

**Comment by marksteele** [comment]
So in the case of a repair, the members fsm coordinator merges the pids for a single group, then sends the group/pids (not crdt) to the divergent node.

The old approach dropped the old set, then added the group+pids. There's a race condition here in that this node may have received more recent data in the interim.

The new approach is that the node receiving the repair merges it's current known set with those in the repair payload (this patch), prunes pids that don't exist, then re-creates the set. The race here is that doing so might fail to remove things that should no longer be there (eg: missed leave calls seen on other nodes but not this one).

So essentially, this is a flaw in the logic of how the members fsm is figuring out the current set. I'm guessing it'll have to ensure that of the responses that it gets (R=2) that they are in agreement, otherwise wait for the third replica to chime in. If there's quorum on the member set, then return that and repair the divergent peer, but that's probably not correct either. 

I'm going to have to dig into the kv code to figure out what the approach is there (I believe there's some reasoning about causality on which replicas dominate based on dvv).

**Comment by cmeiklejohn** [comment]
I don't think it's safe to re-create the set.  Any opposition to just shipping the entire map; that approach might not be the most efficient (we could optimize with deltas later), but it's perfectly safe.  The top-level vector on the map prevents the problems you are witnessing, if I've understood you correctly.

**Comment by marksteele** [comment]
Yup, that's what I was getting at. Not really any good way of sending a delta either (that I can see anyways).

To summarize: when R met, merge, prune, respond. Wait for N then merge/prune/repair (entire map) to any vnodes that are divergent.

Downside of this is we'll be sending the full vnode's map N times to the coordinator which might contain a large number of groups. It'll be correct, not sure how fast it'll be though.

**Comment by marksteele** [comment]
This should fix all the races. The CRDT map is being sent on read.

Pruning occurs on read in the members coordinator fsm, and will trigger vnodes to actually remove from the CRDT so that causal context is available.

**Comment by marksteele** [comment]
The CRDT merge will remove duplicates.

**Comment by cmeiklejohn** [comment]
:+1:

**Pull request merged**
